# Generated by Django 4.2.17 on 2024-12-10 04:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father_guardian_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age_as_on', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(max_length=6)),
                ('aadhaar_no', models.CharField(max_length=12, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='studentregistermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RouteSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(default='Pending', max_length=20)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('pass_applied_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pass_valid_upto', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_selections', to='students.applicantdetails')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_selections', to='admins.route')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residential_address', to='students.applicantdetails')),
            ],
        ),
    ]
