# Generated by Django 4.2.17 on 2024-12-17 06:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_routeselection_fare_amount_routeselection_pass_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now, help_text='Date and time of payment')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid by the user', max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], help_text='Payment method', max_length=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', help_text='Payment status', max_length=10)),
                ('route_selection', models.OneToOneField(help_text='Associated Route Selection for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='students.routeselection')),
            ],
        ),
    ]
