# Generated by Django 4.2.17 on 2024-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('UPI', 'UPI')], help_text='Payment method', max_length=10),
        ),
    ]
