# Generated by Django 4.2.17 on 2024-12-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
